[workspace]
members = [
    "jgsms-cli",
    "jgsms-core",
    "z80-emu",
    "z80-test-runner",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true

[profile.profiling]
inherits = "release"
debug = true

[profile.profiling-lto]
inherits = "profiling"
lto = true
