[workspace]
members = [
    "genesis-core",
    "jgenesis-cli",
    "jgenesis-gui",
    "jgenesis-native-driver",
    "jgenesis-proc-macros",
    "jgenesis-renderer",
    "jgenesis-traits",
    "jgenesis-web",
    "m68000-emu",
    "m68000-test-runner",
    "segacd-core",
    "smsgg-core",
    "snes-core",
    "spc700-emu",
    "spc700-test-runner",
    "wdc65816-emu",
    "wdc65816-test-runner",
    "z80-emu",
    "z80-test-runner",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
base64 = "0.21"
bincode = "2.0.0-rc.3"
bytemuck = "1"
clap = { version = "4", features = ["derive"] }
crc = "3"
env_logger = "0.10"
flate2 = "1"
log = "0.4"
pollster = "0.3"
rand = "0.8"
raw-window-handle = "0.5"
regex = "1"
rfd = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
test-log = "0.2"
thiserror = "1"
toml = "0.8"
windows = "0.51"
wgpu = "0.17"

# This is necessary because the latest published version of rust-sdl2 (0.35.2) uses raw-window-handle 0.4 which is
# incompatible with wgpu using raw-window-handle 0.5
[workspace.dependencies.sdl2]
git = "https://github.com/Rust-SDL2/rust-sdl2.git"
rev = "819ab438ac971a922d6ee1da558822002d343b4e"
features = ["raw-window-handle"]

[profile.dev]

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true

[profile.profiling-lto]
inherits = "profiling"
lto = true
