[package]
name = "m68000-emu"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
bincode = ["dep:bincode"]
memorybus = []

[dependencies]
jgenesis-proc-macros = { path = "../../jgenesis-proc-macros" }
jgenesis-common = { path = "../../jgenesis-common" }

bincode = { workspace = true, optional = true }
log = { workspace = true }

[lints]
workspace = true
