[package]
name = "jgenesis-traits"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.3" }
bytemuck = { version = "1", features = ["derive"] }