[package]
name = "jgenesis-native-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgenesis-traits = { path = "../jgenesis-traits" }
genesis-core = { path = "../genesis-core" }
smsgg-core = { path = "../smsgg-core" }

anyhow = "1"
bincode = "2.0.0-rc.3"
bytemuck = "1"
log = "0.4"
pollster = "0.3"
sdl2 = { workspace = true }
wgpu = "0.17"