[package]
name = "spc700-emu"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgenesis-traits = { path = "../jgenesis-traits" }

bincode = { workspace = true }
log = { workspace = true }